### ISSUE TITLE
2 minutes delay to start to build each time

### ISSUE THREAD

**Issue by kwladyka** [concourse/builder-task#22]
In UI I can see spinning circle on step to build image. It takes around 2 minutes. Building image after this 2 minutes is + 5-20 seconds depend on cache.

I have super simple Dockerfile for tests:
`FROM nginx`

I have installed concourse by `helm` in `kubernetes`.

Summary up: **It takes around 2 minutes freeze each time to start**.
- I was trying it about 10 times with cache and without
- each time UI spinning circle is showing and there is no output in task
- after this this 2 minutes delay it start to build and success

How I run it in `jobs`:
```
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: concourse/builder-task}
          params:
            REPOSITORY: kwladyka/ory-hydra-auth-provider
            TAG: latest
            CONTEXT: auth-provider:master
          inputs:
          - name: auth-provider:master
          outputs:
          - name: image
          caches:
          - path: cache
          run: {path: build}
```

**Comment by larssb** [comment]
I have the same issue. With wait times as high as 17 minutes. I was hoping for the exact opposite in switching from the `docker-image-resource`.

*INFO*

_the parts of the pipeline of interest_
```text
...

(the resources section)
- name: img
  icon: docker
  type: registry-image
  source:
    repository: a/repo
    username: myUser
    password: ((myPassword))

(the JOBS section)
- name: Deploy-ToTest
  serial: true
  plan:
  - get: repo-develop
    trigger: true
  # BUILD IMAGE
  - task: build-image
    file: repo-develop/concourse/tasks/container-img-develop-repo.yml
    privileged: true
  # PUSH IMAGE
  - put: img
    params:
      image: image/image.tar
      additional_tags: repo-develop/.git/ref
...
```

_concourse_
- v5.1.0
- 1 worker
- Concourse is running in Docker containers. 1 for the db, 1 for the web-instance and 1 for the worker

*WHAT HAPPENS*

1. the `repo-develop` step is executed
2. then wait, wait wait for 'x' amount of time. Up to 17 minutes as I write. As @kwladyka writes the UI spinning cirlcle cycles round and round
3. the `build-image` step is executed

However, I can go back to the main overview of configured pipelines in Concourse and then go back to the job I want to view the build output from and I can see it again. Strange.

**Comment by vito** [comment]
What filesystem driver are y'all using for `baggageclaim`? Is it `overlay` or `btrfs`? `overlay` has known performance issues with privileged tasks.

**Comment by kwladyka** [comment]
part of the helm values
```
  worker:
    baggageclaim:
      # volumes:
      ## Driver to use for managing volumes.
      driver: overlay
```
