### ISSUE TITLE
Allow image building without image saving

### ISSUE THREAD

**Issue by cirocosta** [concourse/builder-task#35]
Hey,

Currently, after every `img build` that `builder-task` executes, an `img save`
follows it.

While that's usually the desired case, for leveraging Dockerfiles as a way of
running tests with all of the dependencies, it doesn't make much sense - just
knowing if the build succeeds or fails is enough.

For instance, consider the following job:

```yaml
jobs:
  - name: build
    public: true
    plan:
      - {get: repository, trigger: true}
      - in_parallel:
          fail_fast: true
          steps:
            - task: build-regular
              file: repository/ci/tasks/build.yml
              params: {TARGET: "release"}
              privileged: true
            - task: test
              file: repository/ci/tasks/build.yml
              output_mapping: { image: discard }  # <<<
              params: {TARGET: "test"}
              privileged: true
      - put: container-image
        inputs: [image]
        get_params: {format: oci}
        params:
          image: image/image.tar
```

My proposal is:

- have a `NO_SAVE` (or something with a better name lol) parameter that allows
  `build` to not be followed by a `save`.

Wdyt?

thx!
